### ISSUE TITLE
about dataset

### ISSUE THREAD

**Issue by yjn740116** [dericknganyu/PCANN#1]
I'm sorrry to bother you .Could you please share your data set ,the hdf5 file?
I really need it. Thank you so much.

**Comment by dericknganyu** [comment]
Hello, 

You can find the dataset in this repo
https://github.com/dericknganyu/dl_for_pdes/blob/ca5455aa47efbb975cdac74d2d4cab23dad9bc61/data/datasets.txt

regards,

**Comment by yjn740116** [comment]
Thank you so much for your reply, I get it now .

---- Replied Message ----
| From | ***@***.***> |
| Date | 12/22/2023 02:07 |
| To | dericknganyu/PCANN ***@***.***> |
| Cc | yjn740116 ***@***.***>,
Author ***@***.***> |
| Subject | Re: [dericknganyu/PCANN] about dataset (Issue #1) |

Closed #1 as completed.
